apiVersion: v1
kind: Service

metadata:
  name: xing-appserver-service
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: xing-myapp-tls

spec:
  selector:
    app: xing-myapp
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}  